SCALE = 1.0

# Base parameters scaled
WIDTH_TOP = 210.0 * SCALE
LENGTH_TOP = 160.0 * SCALE
WIDTH_BOTTOM = WIDTH_TOP - 8.0 * SCALE
LENGTH_BOTTOM = LENGTH_TOP - 8.0 * SCALE
BIN_HEIGHT = 240.0 * SCALE

WALL_THICKNESS = 3.0 * SCALE
CORNER_RADIUS = WIDTH_TOP * 0.125  # ~12.5% of width
LID_CORNER_RADIUS = 18.0 * SCALE
EDGE_FILLET_RADIUS = 3.0 * SCALE

GROOVE_WIDTH = 5.0 * SCALE
GROOVE_DEPTH = 1.5 * SCALE
GROOVE_COUNT_LONG = 4
GROOVE_COUNT_SHORT = 2

TRAP_LIP_HEIGHT = 10.0 * SCALE
TRAP_LIP_WIDTH = 5.0 * SCALE
TRAP_Z_OFFSET = 5.0 * SCALE

RING_HEIGHT = 20.0 * SCALE
RING_TOLERANCE = 3.0 * SCALE

RING_WIDTH_OUTER = WIDTH_TOP - 2*WALL_THICKNESS - RING_TOLERANCE
RING_LENGTH_OUTER = LENGTH_TOP - 2*WALL_THICKNESS - RING_TOLERANCE
RING_WIDTH_INNER = RING_WIDTH_OUTER - 2*WALL_THICKNESS
RING_LENGTH_INNER = RING_LENGTH_OUTER - 2*WALL_THICKNESS

SNAP_TAB_WIDTH = 10.0 * SCALE
SNAP_TAB_DEPTH = 1.5 * SCALE

LID_THICKNESS = 5.0 * SCALE
LID_TOLERANCE = 2.0 * SCALE

# Hinge dimensions
HINGE_KNUCKLE_RADIUS = 5.0 * SCALE
HINGE_KNUCKLE_HEIGHT = 10.0 * SCALE
HINGE_PIN_RADIUS = 2.0 * SCALE
HINGE_TOLERANCE = 0.5 * SCALE
