SCALE = 1.0

# Base parameters scaled
WIDTH_TOP = 210.0 * SCALE
LENGTH_TOP = 160.0 * SCALE
WIDTH_BOTTOM = 190.0 * SCALE
LENGTH_BOTTOM = 145.0 * SCALE
BIN_HEIGHT = 240.0 * SCALE

WALL_THICKNESS = 3.0 * SCALE
CORNER_RADIUS = 40.0 * SCALE
EDGE_FILLET_RADIUS = 3.0 * SCALE

GROOVE_WIDTH = 5.0 * SCALE
GROOVE_DEPTH = 1.5 * SCALE
GROOVE_COUNT_LONG = 4
GROOVE_COUNT_SHORT = 2

TRAP_LIP_HEIGHT = 10.0 * SCALE
TRAP_LIP_WIDTH = 5.0 * SCALE
TRAP_Z_OFFSET = 5.0 * SCALE

RING_HEIGHT = 20.0 * SCALE
RING_TOLERANCE = 3.0 * SCALE

RING_WIDTH_OUTER = WIDTH_TOP - 2*WALL_THICKNESS - RING_TOLERANCE
RING_LENGTH_OUTER = LENGTH_TOP - 2*WALL_THICKNESS - RING_TOLERANCE
RING_WIDTH_INNER = RING_WIDTH_OUTER - 2*WALL_THICKNESS
RING_LENGTH_INNER = RING_LENGTH_OUTER - 2*WALL_THICKNESS

SNAP_TAB_WIDTH = 10.0 * SCALE
SNAP_TAB_DEPTH = 1.5 * SCALE

LID_THICKNESS = 5.0 * SCALE
LID_TOLERANCE = 2.0 * SCALE
